"""Small deterministic policy/composition generators for Lev.

These examples are generated by Python, not by asking an LLM for labels.  The
same rule evaluator that creates a record's label also verifies it.  The goal
is to teach the model to connect facts to decisions and to create useful
minimal-pair diagnostics without reproducing Kev's full generator yet.
"""

from __future__ import annotations

import random
from typing import Any


SHAPES: dict[str, Any] = {
    "atom": 0,
    "negation": ("not", 0),
    "conjunction": ("and", 0, 1),
    "disjunction": ("or", 0, 1),
    "exception": ("unless", 0, 1),
    "conditional": ("if", 0, 1, 2),
    "nested_and": ("and", ("and", 0, 1), 2),
    "nested_or": ("or", 0, ("or", 1, 2)),
}


def evaluate_rule(tree: Any, facts: dict[str, bool]) -> bool:
    if isinstance(tree, int):
        return facts[f"fact_{tree}"]
    operation, *children = tree
    values = [evaluate_rule(child, facts) for child in children]
    if operation == "not":
        return not values[0]
    if operation == "and":
        return all(values)
    if operation == "or":
        return any(values)
    if operation == "unless":
        return values[0] and not values[1]
    if operation == "if":
        return values[1] if values[0] else values[2]
    raise ValueError(f"unknown operation {operation}")


def render_rule(tree: Any, names: list[str], style: int) -> str:
    if isinstance(tree, int):
        return names[tree]
    operation, *children = tree
    parts = [render_rule(child, names, style) for child in children]
    if style == 0:
        if operation == "not":
            return f"NOT ({parts[0]})"
        if operation == "unless":
            return f"({parts[0]}) UNLESS ({parts[1]})"
        if operation == "if":
            return f"IF ({parts[0]}) THEN ({parts[1]}) ELSE ({parts[2]})"
        return f"({f' {operation.upper()} '.join(parts)})"
    if operation == "not":
        return f"the condition '{parts[0]}' is false"
    if operation == "unless":
        return f"{parts[0]}, except when {parts[1]}"
    if operation == "if":
        return f"when {parts[0]}, use {parts[1]}; otherwise use {parts[2]}"
    connector = "both" if operation == "and" else "at least one of"
    return f"{connector} these conditions hold: {parts[0]} and {parts[1]}"


def _question(label: bool, source: str, keys: list[str] | None = None) -> dict[str, Any]:
    keys = keys or ["accept", "reject"]
    return {
        "type": "choice",
        "instructions": "Apply the policy to this case.",
        "criteria": {
            key: "The policy permits this case" if key == "accept" else "The policy does not permit this case"
            for key in keys
        },
        "label": "accept" if label else "reject",
        "src": source,
    }


def _record(
    state: dict[str, str],
    label: bool,
    source: str,
    group_id: str,
    pair_id: str,
    sibling: str,
    pair_kind: str,
    shape: str,
) -> dict[str, Any]:
    return {
        "state": state,
        "questions": {"decision": _question(label, source)},
        "_meta": {
            "group_id": group_id,
            "pair_id": pair_id,
            "sibling": sibling,
            "pair_kind": pair_kind,
            "family": shape,
        },
    }


def _compositional_group(rng: random.Random, group_id: str, shape_name: str) -> list[dict[str, Any]]:
    tree = SHAPES[shape_name]
    leaf_count = max(_leaf_indices(tree)) + 1
    facts = {f"fact_{index}": bool(rng.randrange(2)) for index in range(leaf_count)}
    label = evaluate_rule(tree, facts)

    decisive: tuple[str, bool] | None = None
    for key in facts:
        changed = {**facts, key: not facts[key]}
        if evaluate_rule(tree, changed) != label:
            decisive = key, changed[key]
            break
    if decisive is None:
        # A random assignment can occasionally make a fact irrelevant for the
        # chosen tree.  Try the complement before giving up on the group.
        facts = {key: not value for key, value in facts.items()}
        label = evaluate_rule(tree, facts)
        for key in facts:
            changed = {**facts, key: not facts[key]}
            if evaluate_rule(tree, changed) != label:
                decisive = key, changed[key]
                break
    if decisive is None:
        raise ValueError(f"could not find a decisive fact for {shape_name}")

    deciding_key, deciding_value = decisive
    relevant = {**facts, deciding_key: deciding_value}
    irrelevant = {**facts, "routing_reference": not facts.get("routing_reference", False)}
    names = [f"fact {index} is {'true' if facts[f'fact_{index}'] else 'false'}" for index in range(leaf_count)]
    policy_styles = [0, 1]
    style = rng.choice(policy_styles)
    policy = f"Approve exactly when {render_rule(tree, names, style)}. Otherwise reject. The routing reference is irrelevant."

    records = []
    for pair_kind, pair_facts in (("relevant", (facts, relevant)), ("irrelevant", (facts, irrelevant))):
        pair_id = f"{group_id}/{pair_kind}"
        for sibling, values in zip(("a", "b"), pair_facts):
            state = {
                "policy": policy,
                "case": " ".join(
                    f"{key.replace('_', ' ')} is {'true' if value else 'false'}."
                    for key, value in values.items()
                ),
            }
            records.append(
                _record(
                    state,
                    evaluate_rule(tree, values),
                    f"composition_{shape_name}",
                    group_id,
                    pair_id,
                    sibling,
                    pair_kind,
                    shape_name,
                )
            )
    return records


def _leaf_indices(tree: Any) -> set[int]:
    if isinstance(tree, int):
        return {tree}
    return set().union(*(_leaf_indices(child) for child in tree[1:]))


def _policy_group(rng: random.Random, group_id: str) -> list[dict[str, Any]]:
    amount = rng.choice([50, 100, 150, 250])
    verified = bool(rng.randrange(2))
    priority = bool(rng.randrange(2))
    facts = {"amount": amount, "verified": verified, "priority": priority}
    policy = "Approve when the customer is verified AND the amount is at most 150, unless the case is priority."

    def label(values: dict[str, Any]) -> bool:
        return (values["verified"] and values["amount"] <= 150) or values["priority"]

    base = label(facts)
    edited = {**facts, "amount": 250 if amount <= 150 else 100}
    if label(edited) == base:
        edited = {**facts, "verified": not verified}
    nuisance = {**facts, "routing_reference": rng.randint(100, 999)}
    records = []
    for pair_kind, pair_facts in (("relevant", (facts, edited)), ("irrelevant", (facts, nuisance))):
        pair_id = f"{group_id}/{pair_kind}"
        for sibling, values in zip(("a", "b"), pair_facts):
            state = {
                "policy": policy,
                "case": " ".join(
                    f"{key.replace('_', ' ')} is {str(value).lower()}." for key, value in values.items()
                ),
            }
            records.append(
                _record(state, label(values), "legacy_policy", group_id, pair_id, sibling, pair_kind, "policy")
            )
    return records


def build_synthetic(source: str, count: int, rng: random.Random) -> list[dict[str, Any]]:
    """Build exactly ``count`` records, preserving complete four-row groups when possible."""
    records: list[dict[str, Any]] = []
    group_index = 0
    while len(records) < count:
        group_id = f"{source}/{group_index}"
        if source == "legacy_policy":
            records.extend(_policy_group(rng, group_id))
        elif source == "compositional":
            shape = rng.choice(tuple(SHAPES))
            records.extend(_compositional_group(rng, group_id, shape))
        else:
            raise ValueError(f"unknown synthetic source {source}")
        group_index += 1
    return records[:count]
